version: "3.8"

services:
  web:
    build: .
    container_name: sales_trading_app
    command: gunicorn --bind 0.0.0.0:8000 sales_trading_app.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: sales_trading_db
    restart: always
    environment:
      POSTGRES_DB: sales_trading_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sales_trading_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
